/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "Labels-Primary": "#000",
        "bg-bg-overlay": "rgba(0, 0, 0, 0.2)",
        "bg-bg-tertiary": "#f1f0ef",
        "bg-bg-primary": "#fff",
        "fg-fg-tertiary": "#79716b",
        "fg-fg-primary": "#27211b",
        "border-border-white": "#fff",
        "fg-fg-secondary": "#4f4944",
        "bg-bg-brand-secondary": "#f4dedc",
        "fg-fg-brand-primary": "#b34438",
        "bg-bg-disabled": "#f1f0ef",
        "bg-bg-brand-primary": "#faf0ef",
        "fg-fg-brand-secondary": "#c85c50",
        "Backgrounds-Primary": "#fff",
        "fg-fg-white": "#fff",
        "bg-bg-secondary": "#fafafa",
        "border-border-secondary": "#e5e3e1",
        "bg-bg-brand-solid": "#c85c50",
        "fg-fg-disabled": "#cac6c3",
      },
      spacing: {
        "spacing-spacing-none": "0px",
        "spacing-spacing-md": "16px",
        "spacing-spacing-xl": "24px",
        "spacing-spacing-sm": "12px",
        "spacing-spacing-xs": "8px",
        "spacing-spacing-2xs": "4px",
        "icon-sizing-icon-sizing-md": "24px",
        "icon-sizing-icon-sizing-sm": "20px",
        "spacing-spacing-2xl": "32px",
        "icon-sizing-icon-sizing-xs": "16px",
      },
      fontFamily: {
        "noto-sans-jp": "Noto Sans JP",
        "noto-sans-tc": "Noto Sans TC",
      },
      borderRadius: {
        "spacing-spacing-none": "0px",
        "spacing-spacing-md": "16px",
        "radius-radius-full": "999px",
        "spacing-spacing-xs": "8px",
        "radius-radius-none": "0px",
        "radius-radius-xl": "16px",
        "radius-radius-md": "8px",
        "radius-radius-lg": "12px",
      },
    },
  },
  corePlugins: {
    preflight: false,
  },
};